version: '2'
services:
  example_amqp:
    container_name: example_amqp
    image: rabbitmq:management
    ports:
     - 15672:15672
     - 5672:5672  
  simple-start:
    container_name: control-start
    build: ..
    image: abreits/amqp_e2e
    # ports:
    #  - 5671:5671  # AMQP port TLS/SSL
    #  - 5672:5672  # AMQP port
    volumes:
     - ../../examples/control/startpoint-config:/amqp-e2e/config/
     - ../../logs/control-startpoint:/amqp-e2e/logs/
    # environment:
    # - START=dev # dev starts keep-alive (keep container running), run starts shovel
    #  - LOCAL_CONFIG=<path to config file> # default /config/local/config.json
    #  - REMOTE_CONFIG=<path to config file> # default /config/remote/config.json
    depends_on:
     - "example_amqp"
     - "simple-end" # needs to be up to receive message encryption key
    links:
     - "example_amqp"
  simple-end:
    container_name: control-end    
    image: abreits/amqp_e2e
    volumes:
     - ../../examples/control/endpoint-config:/amqp-e2e/config/
     - ../../logs/control-endpoint:/amqp-e2e/logs/     
    depends_on:
     - "example_amqp"
    links:
     - "example_amqp"